import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { computeInlineScriptHash } from './compute-inline-script-hash.mjs';

const rootDir = process.cwd();
const outputDir = path.join(rootDir, 'dist', 'public');
const tmpDir = path.join(rootDir, 'dist', 'public.tmp');

// U7 (sys-hardening p1): file paths written at build time so the CSP
// string carries the exact hash of the inline theme script.
//
//  - `worker/src/generated-csp-hash.js` is consumed by
//    `worker/src/security-headers.js` to build the Content-Security-
//    Policy value at cold-start. It lives inside the Worker import
//    graph (NOT under `src/generated/`, which is excluded below) so
//    Wrangler bundles it.
//  - `dist/public/.csp-theme-hash` is a plain-text artefact used by
//    the drift audit and by operators checking which hash shipped.
//  - `dist/public/_headers` carries the CSP line with the hash value
//    substituted into the `'sha256-BUILD_TIME_HASH'` placeholder.
const generatedCspHashPath = path.join(rootDir, 'worker', 'src', 'generated-csp-hash.js');
const publicCspHashArtefactPath = path.join(outputDir, '.csp-theme-hash');
const publicHeadersPath = path.join(outputDir, '_headers');

const entries = [
  '_headers',
  'favicon.ico',
  'index.html',
  'manifest.webmanifest',
  'styles',
  'assets',
];

const filterPublicFiles = source => {
  const base = path.basename(source);
  const relative = path.relative(rootDir, source).split(path.sep).join('/');
  const retiredClientFiles = new Set([
    'src/bundles/home.bundle.js',
    'src/surfaces/home/index.jsx',
    'src/surfaces/home/TopNav.jsx',
  ]);

  if (base === '.DS_Store') {
    return false;
  }

  if (retiredClientFiles.has(relative)) {
    return false;
  }

  if (relative === 'src/generated' || relative.startsWith('src/generated/')) {
    return false;
  }

  const appIconPng = relative.startsWith('assets/app-icons/')
    && relative.endsWith('.png')
    && base !== 'app-icon-source.png';
  if (relative.startsWith('assets/') && relative.endsWith('.png') && !appIconPng) {
    return false;
  }

  return true;
};

// Wrap the public-mirror pipeline in try/catch + process.exit(1) for the
// same reason as build-bundles.mjs: under certain Windows + execFileSync
// stdio-ignore conditions, an unhandled async rejection from a chained
// step can settle after the entry's sync body finishes and let Node exit 0,
// hiding the failure from CI. The explicit guard keeps failures loud.
try {
  await rm(tmpDir, { recursive: true, force: true });
  await mkdir(tmpDir, { recursive: true });

  for (const entry of entries) {
    await cp(path.join(rootDir, entry), path.join(tmpDir, entry), {
      recursive: true,
      force: true,
      filter: filterPublicFiles,
    });
  }

  await mkdir(path.join(tmpDir, 'src', 'bundles'), { recursive: true });
  await cp(
    path.join(rootDir, 'src', 'bundles', 'app.bundle.js'),
    path.join(tmpDir, 'src', 'bundles', 'app.bundle.js'),
    { force: true },
  );

  // Render-effect CSS lives next to its effect modules so visual + behaviour
  // stay co-located. Mirror it into the public styles directory so the
  // existing single-link pattern in index.html continues to work without a
  // new module-aware loader.
  await cp(
    path.join(rootDir, 'src', 'platform', 'game', 'render', 'effects', 'effects.css'),
    path.join(tmpDir, 'styles', 'effects.css'),
    { force: true },
  );

  await rm(outputDir, { recursive: true, force: true });
  await cp(tmpDir, outputDir, { recursive: true, force: true });
  await rm(tmpDir, { recursive: true, force: true });

  // U7: compute the inline theme-script SHA-256 from the canonical
  // source (`index.html` at repo root). The build already asserts the
  // copied dist/public/index.html is byte-identical; we hash the
  // repo-root copy so a failing copy step surfaces elsewhere.
  const sourceHtml = await readFile(path.join(rootDir, 'index.html'), 'utf8');
  const cspThemeHash = computeInlineScriptHash(sourceHtml);

  // Write the generated module that `worker/src/security-headers.js`
  // imports. Keep the module tiny so a broken build fails fast with a
  // single responsibility. The file IS committed (with a placeholder
  // value) so fresh clones can run `npm test` before the first build;
  // this step overwrites it with the real hash on every build.
  const generatedModule = [
    '// GENERATED BY scripts/build-public.mjs — do not edit by hand.',
    '// This file is committed so fresh clones can run `npm test` before',
    '// `npm run build` has produced a real hash. Build overwrites this.',
    '',
    `export const CSP_INLINE_SCRIPT_HASH = '${cspThemeHash}';`,
    '',
  ].join('\n');
  await writeFile(generatedCspHashPath, generatedModule, 'utf8');
  await writeFile(publicCspHashArtefactPath, `${cspThemeHash}\n`, 'utf8');

  // Substitute the placeholder token in `_headers`. The source file
  // carries `'sha256-BUILD_TIME_HASH'` twice (once for `script-src`,
  // once for `script-src-elem`); both are rewritten to the real value.
  const headersContent = await readFile(publicHeadersPath, 'utf8');
  const substituted = headersContent.replaceAll("'sha256-BUILD_TIME_HASH'", `'${cspThemeHash}'`);
  if (!substituted.includes(cspThemeHash)) {
    throw new Error(
      '_headers must contain a \'sha256-BUILD_TIME_HASH\' placeholder for the CSP rollout (U7). '
      + 'Restore the placeholder or update scripts/build-public.mjs.',
    );
  }
  await writeFile(publicHeadersPath, substituted, 'utf8');
} catch (error) {
  console.error(error);
  process.exit(1);
}
