import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const rootDir = process.cwd();
const workerDistDir = path.join(rootDir, 'dist', 'worker');
const workerEntry = path.join(rootDir, 'worker', 'src', 'index.js');
const workerOutfile = path.join(workerDistDir, 'index.js');
const workerMetafile = path.join(workerDistDir, 'index.meta.json');
const generatedSpellingPublicRuntime = path.join(workerDistDir, 'spelling-public-runtime.js');

const spellingContentDataPath = path.join(rootDir, 'src', 'subjects', 'spelling', 'data', 'content-data.js');
const spellingWordDataPath = path.join(rootDir, 'src', 'subjects', 'spelling', 'data', 'word-data.js');

function compactWord(word = {}) {
  const output = {
    slug: String(word.slug || ''),
    word: String(word.word || ''),
    year: word.year === '5-6' ? '5-6' : word.year === 'extra' ? 'extra' : '3-4',
    yearLabel: String(word.yearLabel || ''),
    spellingPool: word.spellingPool === 'extra' ? 'extra' : 'core',
    coverageTier: String(word.coverageTier || ''),
    family: String(word.family || ''),
  };
  return Object.fromEntries(Object.entries(output).filter(([, value]) => value !== ''));
}

async function writeSpellingPublicRuntime() {
  const {
    SEEDED_SPELLING_CONTENT_BUNDLE,
    SEEDED_SPELLING_CONTENT_SUMMARY,
    SEEDED_SPELLING_PUBLISHED_SNAPSHOT,
  } = await import(pathToFileURL(spellingContentDataPath).href);

  const words = (Array.isArray(SEEDED_SPELLING_PUBLISHED_SNAPSHOT?.words)
    ? SEEDED_SPELLING_PUBLISHED_SNAPSHOT.words
    : []).map(compactWord);
  const wordBySlug = Object.fromEntries(words.map((word) => [word.slug, word]));
  const snapshot = {
    generatedAt: Number(SEEDED_SPELLING_PUBLISHED_SNAPSHOT?.generatedAt) || 0,
    words,
    wordBySlug,
  };
  const publication = SEEDED_SPELLING_CONTENT_BUNDLE?.publication || {};
  const publishedVersion = Number(publication.publishedVersion) || 0;
  const publishedAt = Number(publication.updatedAt) || 0;
  const releaseId = publication.currentReleaseId || `spelling-r${publishedVersion || 1}`;
  const contentBundle = {
    modelVersion: Number(SEEDED_SPELLING_CONTENT_BUNDLE?.modelVersion) || 6,
    subjectId: 'spelling',
    draft: {
      id: 'worker-public-runtime',
      state: 'draft',
      title: 'Worker public runtime',
      sourceNote: 'Compact public runtime snapshot for Worker bootstrap and Hero read models.',
      provenance: {
        source: 'scripts/build-worker.mjs',
        note: 'Generated from the published spelling snapshot.',
        importedAt: publishedAt,
      },
      wordLists: [],
      words: [],
      sentences: [],
      updatedAt: publishedAt,
    },
    releases: [{
      id: releaseId,
      state: 'published',
      version: publishedVersion || 1,
      title: 'Worker public runtime',
      notes: 'Compact public runtime snapshot for Worker bootstrap and Hero read models.',
      sourceDraftId: 'worker-public-runtime',
      sourceNote: 'Generated from the published spelling snapshot.',
      provenance: {
        source: 'scripts/build-worker.mjs',
        note: 'Generated from the published spelling snapshot.',
        importedAt: publishedAt,
      },
      publishedAt,
      snapshot,
    }],
    publication: {
      currentReleaseId: releaseId,
      publishedVersion: publishedVersion || 1,
      updatedAt: publishedAt,
    },
  };
  const summary = {
    ...SEEDED_SPELLING_CONTENT_SUMMARY,
    publishedReleaseId: SEEDED_SPELLING_CONTENT_SUMMARY?.publishedReleaseId || releaseId,
    publishedVersion: Number(SEEDED_SPELLING_CONTENT_SUMMARY?.publishedVersion) || publishedVersion || 1,
    publishedAt: Number(SEEDED_SPELLING_CONTENT_SUMMARY?.publishedAt) || publishedAt,
    runtimeWordCount: words.length,
  };
  const moduleSource = [
    '// GENERATED BY scripts/build-worker.mjs - do not edit by hand.',
    '// Compact spelling runtime used only by the bundled Cloudflare Worker.',
    `export const SEEDED_SPELLING_PUBLISHED_SNAPSHOT = ${JSON.stringify(snapshot)};`,
    `export const SEEDED_SPELLING_CONTENT_BUNDLE = ${JSON.stringify(contentBundle)};`,
    `export const SEEDED_SPELLING_CONTENT_SUMMARY = ${JSON.stringify(summary)};`,
    'export const SEEDED_SPELLING_PUBLISHED_RELEASE = SEEDED_SPELLING_CONTENT_BUNDLE.releases[0];',
    'export const WORDS = SEEDED_SPELLING_PUBLISHED_SNAPSHOT.words;',
    'export const WORD_BY_SLUG = SEEDED_SPELLING_PUBLISHED_SNAPSHOT.wordBySlug;',
    '',
  ].join('\n');

  await writeFile(generatedSpellingPublicRuntime, moduleSource, 'utf8');
}

function workerAliasPlugin() {
  const aliases = new Map([
    [path.normalize(spellingContentDataPath), generatedSpellingPublicRuntime],
    [path.normalize(spellingWordDataPath), generatedSpellingPublicRuntime],
  ]);

  return {
    name: 'ks2-worker-aliases',
    setup(buildContext) {
      buildContext.onResolve({ filter: /(?:content-data|word-data)\.js$/ }, (args) => {
        const absolutePath = path.normalize(path.resolve(args.resolveDir, args.path));
        const aliasPath = aliases.get(absolutePath);
        return aliasPath ? { path: aliasPath } : null;
      });
    },
  };
}

await mkdir(workerDistDir, { recursive: true });
await writeSpellingPublicRuntime();

const result = await build({
  entryPoints: [workerEntry],
  outfile: workerOutfile,
  absWorkingDir: rootDir,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  sourcemap: false,
  metafile: true,
  legalComments: 'none',
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  plugins: [workerAliasPlugin()],
  logLevel: 'info',
});

await writeFile(workerMetafile, `${JSON.stringify(result.metafile, null, 2)}\n`, 'utf8');

console.log(`Built Worker bundle at ${path.relative(rootDir, workerOutfile)}`);
