// Fresh-worktree preflight: fails fast with an actionable message when
// node_modules is missing. Git worktrees do not share node_modules with
// the primary checkout, so the first `npm test` in a new worktree would
// otherwise produce a cryptic ERR_MODULE_NOT_FOUND stack from deep inside
// a test file. Catching it here keeps the signal clear for anyone
// starting work in a fresh worktree.
//
// correctness-blocker-1: also warns (non-fatal) when the committed
// `worker/src/generated-csp-hash.js` still carries the pre-build
// placeholder sentinel so contributors know to run `npm run build` before
// deploying. Tests must still run, so we only warn.
import { access, readFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import path from 'node:path';

// Sentinel set, not exhaustive. Pick devDependencies that (a) are imported
// during `npm test` (directly or transitively via a bundler step) and (b)
// have zero same-repo fallbacks -- so a missing install produces an
// actionable, non-cryptic failure instead of a deep stacktrace. Adding more
// packages here is cheap (one `access` call each); keep the list small
// enough that a contributor can eyeball it against package.json. Iterating
// devDependencies dynamically was considered and rejected: it couples this
// script to package.json parsing and would flag pure build-only deps that
// `npm test` does not need.
const REQUIRED_PACKAGES = ['react', 'esbuild'];

async function isInstalled(packageName) {
  const pkgJson = path.join('node_modules', packageName, 'package.json');
  try {
    await access(pkgJson, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

const missing = [];
for (const pkg of REQUIRED_PACKAGES) {
  if (!await isInstalled(pkg)) {
    missing.push(pkg);
  }
}

if (missing.length > 0) {
  console.error(
    `Missing node_modules (${missing.join(', ')}) — run "npm install" from this worktree root before "npm test". Git worktrees do not share node_modules with the primary checkout.`,
  );
  process.exit(1);
}

// Soft-warn if the committed CSP hash module still holds the pre-build
// placeholder. The file is regenerated by `scripts/build-public.mjs`, so a
// placeholder simply means the contributor has not run `npm run build`
// yet. Tests are allowed to proceed — this is informational only.
const generatedCspHashPath = path.join('worker', 'src', 'generated-csp-hash.js');
try {
  const generatedCspContent = await readFile(generatedCspHashPath, 'utf8');
  if (generatedCspContent.includes('PLACEHOLDER_PRE_BUILD_HASH')) {
    console.warn(
      `[preflight-test] ${generatedCspHashPath} still carries the pre-build placeholder sentinel. `
      + 'Tests will run, but the CSP will not validate the inline theme script. '
      + 'Run `npm run build` before deploying so the real sha256 hash is injected.',
    );
  }
} catch {
  // The file might be missing on a truly fresh clone from before this
  // fix landed. Not fatal — tests import paths will surface the real
  // error in that case.
}
